### ISSUE TITLE
Future: add serializers for querysets

### ISSUE THREAD

**Issue by wpjunior** [hmarr/mongoengine#230] opened 2011-07-12 11:53 UTC
example:
# serializing

Person.objects.serialize('xml')
Person.objects.serialize('yaml')

a = open('output.xml', 'wb')
Person.objects.serialize('xml', fields=('data.name', 'endr'), out=a)
# deserialize

data = open('input.xml', 'rb').read()
objs = Person.objects.deserialize('xml', data)

for obj in objs;
    obj.save()

**Comment by wpjunior** [comment] 2011-07-12 12:03
if you need help, I am willing to contribute to the code :-)

**Comment by rozza** [comment] 2011-07-12 13:26
Duplicate of #210

**Closed as completed by rozza** 2011-07-12 13:26 UTC
