### ISSUE TITLE
FileField requires file object instead of file-like object

### ISSUE THREAD

**Issue by ndrsn** [hmarr/mongoengine#485] opened 2012-04-18 10:34 UTC
GridFS requires the argument to `put()` to be a file-like object that implements `read()`, yet mongoengine demands the value passed to `put()` to be an [actual instance of a file object](https://github.com/hmarr/mongoengine/blob/master/mongoengine/fields.py#L938) 

Django's `InMemoryUploadedFile` and `TemporaryUploadedFile` classes, both of which implement `read()` therefore cannot be passed directly to a `FileField`, but must be converted to an actual string or file object. In my case, it's not terribly big deal, but it seems a bit counterintuitive. Is this discrepancy between GridFS and MongoEngine by design?

**Comment by rozza** [comment] 2012-04-18 12:55
Not by design - probably just an oversight - want to do a pull request? and I'll merge.

**Comment by ndrsn** [comment] 2012-04-18 13:04
To be honest, I'm not yet sure how to fix it. I fixed it in my Django app by checking the type of the `UploadedFile` and passing a string if `InMemoryUploadedFile` and the actual file handle if `TemporaryUploadedFile`

I have tried changing `isinstance(value, file)` to `hasattr(value, 'read')` but that throws an error. I'll have to look into it and get back to you.

**Comment by rozza** [comment] 2012-04-25 11:45
Thanks swashbuckler this is now merged and will be out in 0.6.7

**Closed as completed by rozza** 2012-04-25 11:45 UTC
