### ISSUE TITLE
len(Model.objects) and Model.object.count() don't always work

### ISSUE THREAD

**Issue by j0hnsmith** [hmarr/mongoengine#150] opened 2011-04-05 02:06 UTC
I've got a queryset of 1000's of instances however when I try to find out exactly how many I only get 21 (I assume this the the number returned before truncation in the interactive interpreter). This doesn't happen all the time.

**Comment by rozza** [comment] 2011-05-18 10:17
I believe this may be related to #166, #152  which have been fixed.

However, it does seem to be different enough - can you confirm what mongoengine you are running (pypy, master or dev) and what version of pymongo?

Also any test code would be awesome, so I can see if I can replicate.

**Comment by j0hnsmith** [comment] 2011-05-18 15:22
I'm using 0.4 from pypy (via pip). I changed my code to get around the problem so unfortunately don't have an example, however I also think it's related to #152 & #166.

**Comment by rozza** [comment] 2011-05-18 15:38
Thanks for getting back to me.  I'll close this ticket for now in the belief the issue is fixed in dev.

**Closed as completed by rozza** 2011-05-18 15:38 UTC
