### ISSUE TITLE
optional ImageField

### ISSUE THREAD

**Issue by wpjunior** [hmarr/mongoengine#293] opened 2011-09-28 16:43 UTC
if the PIL library was found activate the ImageField
can inspire us in:
http://code.google.com/p/django-stdimage/
https://code.djangoproject.com/browser/django/trunk/django/db/models/fields/files.py#L318

**Comment by rozza** [comment] 2011-10-08 15:10
Duplicate of your #298 - so closing this ticket!

btw - great work @wpjunior !

**Closed as completed by rozza** 2011-10-08 15:10 UTC
