### ISSUE TITLE
Multiple calls to system.namespaces.find({})

### ISSUE THREAD

**Issue by andrewmlevy** [hmarr/mongoengine#504] opened 2012-05-17 17:07 UTC
We are seeing a ton of these requests in our logs (we are using mongoengine v0.6.2 and MongoDB 2.0.4). It seems like the Ruby ODM also faced this same bug:

https://github.com/mongoid/mongoid/issues/1465

Please advise on the best way to proceed. This is what our logs are filled with:

Thu May 17 12:58:50 [conn625503] getmore OUR_DB_NAME.system.namespaces query: { $query: {} } cursorid:6892775431846265211 nreturned:125 reslen:7089 20638ms

Thanks

**Comment by rozza** [comment] 2012-05-17 20:29
Will investigate tomorrow and report back here - can you provide  a test case that reproduces.

**Comment by rozza** [comment] 2012-05-17 21:38
I can't reproduce or find evidence of `getMore` being called where you wouldnt expect it.  

Drivers lazily perform a "getMore" operation as needed on the cursor to get more data.  Just to confirm you have no unbound queries that you are iterating through?

For example this would loop through all objects in a `Docs` class but wouldn't have a `query: { $query: {}}` against it.

```
[doc for doc in Docs.objects()]
```

Logs would contain entries like:

```
Thu May 17 22:31:23 [conn3] getmore mongoenginetest.docs query: { _types: "Docs" } cursorid:418024121888561251 nreturned:8722 reslen:802444 9ms
```
- You'll notice `_types` is added automatically to the query as in my example `Docs` has allow inheritance as True.

We don't call `system.namespaces` explicitly in the code and this is done by the driver.

So I need more information to be able to help out:
- What version of pyMongo
- What version of MongoEngine are you running?
- Any frameworks?
- Can you reproduce?  I've ran the test suite and only see a single call to namespaces (caused by ensureIndex and the driver checking namespaces).

**Comment by rozza** [comment] 2012-06-19 13:16
@andrewmlevy any feedback?

**Comment by andrewmlevy** [comment] 2012-06-19 17:01
Ross -- thanks for checking in. Lets close the issue for now. We noticed it was more of an issue when our working set grew too large, and noticed a lot of calls to system.namespace in our logs. We'll let you know if we can recreate the issue. I appreciate the followup.

**Comment by rozza** [comment] 2012-06-19 21:11
ok - closing for now

**Closed as completed by rozza** 2012-06-19 21:11 UTC
