### ISSUE TITLE
Issues with Custom Managers and Testing

### ISSUE THREAD

**Issue by KMontag42** [hmarr/mongoengine#551] opened 2012-08-01 19:16 UTC
Not sure where to put this:

Hello you studly MongoEngine devs!!

Currently I am working on a project using Django and MongoEngine, and I am trying to define a custom manager for some of my models.

Here is the code for my model class:
import django
from django.db import models
from managers import *
from mongoengine import *
from common.models import BaseDocument
from datetime import datetime

class BaseActivity(BaseDocument):
created_time = DateTimeField()
updated_time = DateTimeField(default = datetime.now())
performed_by = ListField() #user type and id
performed_by_url = StringField() #posisbly change to URLField() depending on how we want to do these
performed_on = ListField() #user type and id
performed_on_url = StringField()
location = StringField()
# objects = ActivityManager

meta = {'allow_inheritance' : True, 'queryset_class' : ActivityManager}
# BaseActivity.add_to_class('objects', ActivityManager(BaseActivity, BaseActivity.objects._collection))

I left those comments in because those are other measures that I have tried with this class, none of which worked, so I stuck to the documented way to perform this action.

Here is the manager code that I am using:
from django.db import models
from mongoengine import *
from mongoengine.queryset import QuerySetManager, QuerySet

class ActivityManager(QuerySetManager):

def **init**(self, *args):
    super(QuerySetManager, self).**init**()

def get_recent_by_date(self, date):
    """
    gets recent activity from the start date given, to the current time
    """
    query_data = self.objects.filter(created_time__gte = date )
    return query_data

def get_recent_by_user(self, user):
    """
    gets activity from the given user
    """
    query_data = self.objects.filter(performed_by= user)
    return query_data

def get_activity(self, start_date, end_date):
    """
    gets all activity from the start date to the end date
    """
    query_data = self.objects.filter(created_time__lt = end_date).filter(created_time__gte = start_date)
    return query_data

This all seems pretty straight forward, nothing here looks suspicious to me.

Here is the test code:
import sys
from django.test import TestCase
from django.test.client import Client
from ..managers import *
from ..models import BaseActivity
from datetime import datetime

class ManagerTests(TestCase):

def setUp(self):
    self.base_activity = BaseActivity(
        created_time     = datetime.today(),
        updated_time     = datetime.now(),
        performed_by     = ('Artist', 1),
        performed_by_url = 'Kyle',
        performed_on     = ('Venue', 1),
        performed_on_url = 'HoB',
        location         = "Boston",
    )
    self.base_activity2 = BaseActivity(
        created_time     = datetime(2011,7,1),
        updated_time     = datetime.now(),
        performed_by     = ('Artist', 1),
        performed_by_url = 'Kyle',
        performed_on     = ('Venue', 1),
        performed_on_url = 'HoB',
        location         = "Boston",
    )

```
self.base_activity.save()
self.base_activity2.save()
```

def tearDown(self):
    BaseActivity.objects.delete()

def test_get_recent_by_date(self):
    #print self.base_activity.objects.get_recent(datetime(2012, 7, 31))
    self.assertEqual(len(self.base_activity.objects.get_recent_by_date(datetime(2012, 7, 30))), 1)

def test_get_recent_by_user(self):
    self.assertEqual(len(self.base_activity.objects.get_recent_by_user(('Artist', 1))), 2)

def test_get_activity(self):
    self.assertEqual(len(self.base_activity.objects.get_activity(datetime(2012,7,29),datetime.today())), 1)

Here is the error that I get :
ERROR: test_get_recent_by_user (activity.tests.managers.ManagerTests)

Traceback (most recent call last):
File "/home/napa/kyle/source/trunk/napa/activity/tests/managers.py", line 30, in setUp
self.baseactivity.save()
File "/home/napa/kyle/source/trunk/napa/common/models.py", line 29, in save
return super(BaseDocument, self).save(_args, *_kwargs)
File "/home/napa/kyle/source/trunk/env/local/lib/python2.7/site-packages/mongoengine/document.py", line 194, in save
collection = self.class_.objects._collection
AttributeError: 'ActivityManager' object has no attribute '_collection'

Any insight with this issue would be greatly appreciated. As it seems, I have done everything correct for using a custom QuerySetManager, but inheritance doesn't seem to be right.

There is very little (if any) documentation on this type of thing, and from the other stuff I found in my searches (i.e. that monkeypatch) still doesn't fix this issue.

This seems like a big issue since it could take down an entire site, but if this is an error of mine please point it out!!

Thanks so much for any assistance you can give!
Kyle

**Comment by rozza** [comment] 2012-08-03 07:10
duplicate of MongoEngine/mongoengine#53

**Closed as completed by rozza** 2012-08-03 07:10 UTC
