### ISSUE TITLE
Python Sigfault (sometime)

### ISSUE THREAD

**Issue by Ankhbayar** [hmarr/mongoengine#145] opened 2011-03-29 07:39 UTC
Some time python shell is down. (With django shell)
# sigfault.py

```
import mongoengine 
mongoengine.connect("seg_fault")
class User(mongoengine.Document):
    username = mongoengine.StringField()

class Post(mongoengine.Document):
    title = mongoengine.StringField()
    body = mongoengine.StringField()
    username = mongoengine.StringField()
    user = mongoengine.ReferenceField(User)

    def save(self):
        if self.user:
            self.username = self.user.username
        # Orignal save
        super(Post, self).save()

User.drop_collection()
Post.drop_collection()

user = User(username = "mongo")
user.save()

p1 = Post(title = "Hello Mongo", body = "using Mongoengine", user = user)
p1.save()

p2 = Post(title = "Hello PyMongo", body = "using Mongoengine", user = user)
p2.save()

p3 = Post(title = "Hello PyMongo", body = "using Mongoengine. No user")
p3.save()

all_list = list( Post.objects.all())

print "Simple query -- len = 3 ", len(all_list) # OK normal

# Filter ref 
by_user = list(Post.objects.filter(user = user))

print "Filter ref -- len = 2", len(by_user) # OK normal

# Filter string
by_username = list( Post.objects.filter(username = user.username))

print "Filter ref -- len = 2", len(by_username)

# In AbNormal stringfield == object() Raise
try:
    by_username = list( Post.objects.filter(username = object() ))
except:
    print "Good raise stringfield = object()" # OK abnormal

# In AbNormal stringfield == new DocumentIntance() Raise
try:
    by_username = list( Post.objects.filter(username = User() ))
except:
    print "Good raise stringfield = new DocumentIntance()"

try:
    # In AbNormal string field == DocumentInstance !!!!!!!
    by_username = list( Post.objects.filter(username = user))
except:
    print "Good raise stringfield = DocumentInstance"  # NG sigfault (sometime)
```

**Comment by rozza** [comment] 2011-05-19 09:05
Hi,

Not sure where to go with this ticket, I can't reproduce.  Can you give some information on your system.  Python / pymongo / django versions etc...

**Comment by Ankhbayar** [comment] 2011-05-19 09:13
Thanks for reply.
PyMongo Lastest with C extention.
Mongoengine Latest. 
Django 1.2.5

$ django-admin.py createproject demo
added in settings.py
settings.py:

```
from  mongoengine import connection
try:
    connection.connect('test_database'))
except:
    pass
```

$ python manage.py shell
....

I guess to problem is http://api.mongodb.org/python/current/faq.html#does-pymongo-work-with-mod-wsgi

**Comment by rozza** [comment] 2011-05-19 09:25
Hmm - well if its all in the shell, it shouldn't be mod-wsgi or  Python sub interpreters.

Have you seen it without the pymongo C extension at all?

**Comment by Ankhbayar** [comment] 2011-05-19 11:18
try this code. 

# In Python shell :

```
import mongoengine 
import pymongo
import decimal

from mongoengine import connection

connection.connect("seg_fault")



class User(mongoengine.Document):
    name = mongoengine.StringField()


class Post(mongoengine.Document):
    title = mongoengine.StringField()
    dict = mongoengine.DictField()

User.drop_collection()
Post.drop_collection()

u1 = User.objects.create(name = "mongo")

p1 = Post.objects.create(title = "Mongoengine", dict = {'readcount' : 0, 'tags' : ['mongo', 'python'], 'author' : 'mongo' } )

try:
    p1 = Post.objects.create(title = "Mongoengine", dict = {'readcount' : 0, 'tags' : ['mongo', 'python'], 'author' : User() } )
except:
    print "Good raise "

try:
    p1 = Post.objects.create(title = "Mongoengine", dict = {'readcount' : 0, 'tags' : ['mongo', 'python'], 'author' : object() } )
except:
    print "Good raise "

try:
    p1 = Post.objects.create(title = "Mongoengine", dict = {'readcount' : 0, 'tags' : ['mongo', 'python'], 'author' : decimal.Decimal() } )
except:
    print "Good raise "

try:
    p1 = Post.objects.create(title = "Mongoengine", dict = {'readcount' : 0, 'tags' : ['mongo', 'python'], 'author' : u1 } )
except:
    print "Good raise"

# Switch connection
other_db =  connection._get_db("another_db")
other_db.collection_names()

##################################   
# In model field for standart model 
##################################
try:
    # In AbNormal stringfield == object() Raise
    by_username = list( Post.objects.filter(title = object() ))
except:
    print "Good raise"

try:
    # In AbNormal stringfield == new DocumentIntance() Raise
    by_username = list( Post.objects.filter(title = User() ))
except:
    print "Good raise"

try:
    # In AbNormal stringfield == DocumentIntance() Raise
    by_username = list( Post.objects.filter(title = u1))
except:
    print "Good raise"


##################################   
# In dic field for dynamic model 
##################################
try:
    # In AbNormal stringfield == object() Raise
    by_username = list( Post.objects.filter(dict__author = object() ))
except:
    print "Good raise"

try:
    # In AbNormal stringfield == new DocumentIntance() Raise
    by_username = list( Post.objects.filter(dict__author = User() ))
except:
    print "Good raise"

try:
    # In AbNormal stringfield == DocumentIntance() Raise
    by_username = list( Post.objects.filter(dict__author = u1))
except:
    print "Good raise"
```

# First query is Sometime fail is WSGI enviroment with C extention:

```
try:
...     p1 = Post.objects.create(title = "Mongoengine", dict = {'readcount' : 0, 'tags' : ['mongo', 'python'], 'author' : User() } )
... except:
...     print "Good raise "
... 
/usr/local/lib/python2.7/dist-packages/pymongo-1.11-py2.7-linux-x86_64.egg/bson/__init__.py:466: RuntimeWarning: couldn't encode - reloading python modules and trying again. if you see this without getting an InvalidDocument exception please see http://api.mongodb.org/python/current/faq.html#does-pymongo-work-with-mod-wsgi
  return cls(_dict_to_bson(document, check_keys))
```

**Comment by rozza** [comment] 2011-05-19 11:55
So its a mod-wsgi issue?  Not a shell issue?

Either way it seems to be core mongodb issue with python - have you tried taking the steps mentioned in the link (http://api.mongodb.org/python/current/faq.html#does-pymongo-work-with-mod-wsgi)

**Comment by Ankhbayar** [comment] 2011-05-20 11:20
Yes. 
1. Fail
2. Fail
3. - Working for me. 
But i need performance. That is not mongoengine issue. it is pymongo issue?.

**Comment by Ankhbayar** [comment] 2011-05-20 11:29
That is very hard problem.
Not pymongo. More deeper  in Python GIL issue!!!. 

http://nosql.mypopescu.com/post/365404983/mongodb-pymongo-and-mod-wsgi

How sad :(

**Comment by rozza** [comment] 2011-05-20 11:31
Hmm - not great news.

Closing this ticket as its out the remit of mongoengine.

**Closed as completed by rozza** 2011-05-20 11:31 UTC
