### ISSUE TITLE
Queries over list field are inconsistent

### ISSUE THREAD

**Issue by mitar** [hmarr/mongoengine#498] opened 2012-05-13 23:05 UTC
I have such document definition (excerpt):

```
class User(auth.User):
    connections = mongoengine.ListField(mongoengine.EmbeddedDocumentField(Connection))
```

I found different inconsistencies. Doing:

```
user.connections = []
user.save()
```

Deletes the field from the document. Then doing:

```
models.User.objects(connections=[])
models.User.objects(connections=None)
```

Return different results. If I use `pull` atomic operation, it sets the field to `[]`. So the above queries work exactly in different way.

The solution is probably then to do:

```
models.User.objects(connections__in=([], None))
```

But the problem is if you want to negate this. If you want to find all objects where `connections` is not empty. Of course this is not right:

```
models.User.objects(connections__ne=[])
```

Because it gets those objects where field does not exist.

And:

```
models.User.objects(connections__ne=None)
```

Returns also objects with empty lists. This:

```
models.User.objects(connections__nin=([], None))
```

Does not really work, as it in fact the same as:

```
models.User.objects(connections__ne=[])
```

What does work is:

```
models.User.objects(connections__not__in=([], None))
```

Things would be much easier if field would not be deleted when set to empty list. `None` and `[]` should probably mean the same for lists. And `nin` and `not__in` should do the same.

**Comment by mitar** [comment] 2012-05-13 23:09
Ah, yes, also `size` does not really solve the problem:

```
models.User.objects(connections__size__gt=0)
```

Seems to always return empty list. While:

```
models.User.objects(connections__size__ne=0)
```

always returns objects.

**Comment by rozza** [comment] 2012-05-14 07:36
Hi,

`[]` and `none` are different values and are both valid and will have different results when querying against, you may want to look at different types in the bsonspec.org.

```
user.connections = []
user.save()

User.objects(connections=[])
User.objects(connections=None)
```

Both of the above are valid queries and should return different values as they are testing for different values.  If you want to tell if a document has a field then you should use `exists`:

```
User.objects(connections__exists=True)
```

Now the question is, is mongoengine doing something wrong when setting to an empty list?  As far as I can tell no, but you do need to understand mongoDB to understand the behaviours here.

**Comment by mitar** [comment] 2012-05-14 08:08
OK. Then I will be more precise:

```
user.connections = []
user.save()
```

Should set the field to `[]` and not delete it.

```
models.User.objects(connections__nin=([], None))
models.User.objects(connections__not__in=([], None))
```

Should be the same. It is not. It seems:

```
models.User.objects(connections__nin=([], None)) == models.User.objects(connections__nin=([],))
```

These two should also return the same:

```
models.User.objects(connections__size__gt=0)
models.User.objects(connections__size__ne=0)
```

They do not.

**Comment by rozza** [comment] 2012-05-14 08:21
OK thanks for the update,  I think this is a duplicate ticket on dealing with defaults and deletions.  

btw a testcase would be much easier to read and understand and has the benefit of allowing the issue to be repeated easily.

**Comment by rozza** [comment] 2012-05-14 08:24
Cant find the ticket - so reopening.  Will investigate today.

**Comment by mitar** [comment] 2012-05-14 09:00
I made tests. Enjoy. :-)

Please make sure that `connections__not__in` works as it works now. This is currently the only working way I can use in my code. So don't fix it by making it work as `connections__nin`. Fix the other way around. :-)

**Comment by mitar** [comment] 2012-05-14 09:02
BTW, there seems to be a difference between:

```
p = Parent()
p.connections = []
p.save()
```

and:

```
p = Parent.objects()[0]
p.connections = []
p.save()
```

First stores empty list in the database. The second deletes the field.

**Comment by rozza** [comment] 2012-05-14 09:51
Thanks.  btw I'm surprised `not__in` works differently to `nin`

**Comment by mitar** [comment] 2012-05-14 10:47
Luckily for me. Because `nin` does not work as I would need, while `not__in` does. :-)

**Comment by rozza** [comment] 2012-05-14 11:33
ok, well seems this expected behaviour.  

Changing to a empty list currently unsets the field, there was long discussions about it on the mailing list with opposing points of view and not storing won out - https://github.com/MongoEngine/mongoengine/blob/master/tests/document.py#L1638-1640

I'm not to happy about the whole _delta aspect and performance aspects so this will be fixed in 0.7 and it will break peoples code.  I have to start moving people away from `.save` as its generally harmful and is too magical.

**Closed as completed by rozza** 2012-05-14 11:33 UTC

**Comment by rozza** [comment] 2012-05-14 11:35
See: mongoengine/mongoengine#19

**Comment by mitar** [comment] 2012-05-14 11:37
There are much more tests then just the question of how assignment of `[]` is done. So then just throw the first group of tests away (or overwrite with the second one). But later tests will still fail.

**Comment by mitar** [comment] 2012-05-14 11:37
(So, don't close this ticket so fast.)

**Comment by mitar** [comment] 2012-05-14 11:37
Why is `.save` generally harmful?

**Comment by rozza** [comment] 2012-05-14 11:57
@mitar - firstly, thanks for reporting these - its good and I dont mean to appear blunt - and I will fix / change behaviour in 0.7.

All the tests are because of how setting / unsetting [] is handled, the syntax in the tests test mongoDB and are aside issue from this.

`.save` is harmful because its not atomic and by pymongo default overwrites the whole document.  MongoEngine adds some magic change tracking which converts changes to `$set` and $unset` but as you see there are edge cases, these will be looked at in 0.7 and be marked on a Field level.

**Comment by mitar** [comment] 2012-05-14 11:59
> All the tests are because of how setting / unsetting [] is handled, the syntax in the tests test mongoDB and are aside issue from this.

Difference between `nin` and `not__in` probably does not have anything with this? And difference between `size__gt` and `size__ne`?

**Comment by rozza** [comment] 2012-05-14 12:01
@mitar - ok I'll review and post finding here :)

**Comment by mitar** [comment] 2012-05-14 12:08
I made new tests and pull request based on what you described above as expected behavior.

They still fail.

**Comment by rozza** [comment] 2012-05-14 12:31
So `connections__size__ne` translates to `{'connections.size': {'$ne': 0}}` as `$size` only takes a number not a sub element.

`connections__not__in` translates to: `{'connections': {'$not': {'$in': [[], None]}}}` as `$not` takes a sub element.

These queries are passed back raw to pymongo / mongoDB and the results come from them.

**Comment by mitar** [comment] 2012-05-14 12:33
Then first should probably be prevented? And for second there should be some documentation, that `nin` is not the same as `not__in`?

**Comment by rozza** [comment] 2012-05-14 12:39
Possibly we could prevent `size__ne` but that would potentially add lots of complexity and slow down the query translator.

`not__in` and `nin` work the same for me .  I changed the buggy `save` to be updates and commented out the buggy size queries: http://pastie.org/private/hqfotqqylrdowsrjsqig

**Comment by mitar** [comment] 2012-05-14 12:48
`p.update(set__connections=None)` is not the same as `p.update(unset__connections=1)`. Try later, and tests will fail.

(So it seems we have three things to check, connections field not existing, connections field being null, connections field being [].)

**Comment by rozza** [comment] 2012-05-14 12:58
True but setting something something to None is not the same as unsetting it, so those are two different use cases.

Seems, `not__in` and `nin` do behave slightly differently, `not__in` requires the field to exist.

**Comment by mitar** [comment] 2012-05-14 12:59
> True but setting something something to None is not the same as unsetting it, so those are two different use cases.

Yes, and my original code was doing unsetting (even if I was assigning None).

**Comment by rozza** [comment] 2012-05-14 14:13
Ah to do a delete dont do a setattr!  `del user.connections`

**Comment by mitar** [comment] 2012-05-14 14:14
I know now. But because how `.save` works, it was delete. :-)
