### ISSUE TITLE
Exception in latest version

### ISSUE THREAD

**Issue by StuartMitchell** [hmarr/mongoengine#39] opened 2010-04-12 22:51 UTC
I get the following exception when deriving from Class that is derived from Document.

```
class RangedParameters(Measurements):
 File "/home/smit023/bzr/ipcim/song_ui/src/mongoengine/mongoengine/base.py", line 235, in __new__
new_class = super_new(cls, name, bases, attrs)
File "/home/smit023/bzr/ipcim/song_ui/src/mongoengine/mongoengine/base.py", line 177, in __new__
or (DoesNotExist,), module))
File "/home/smit023/bzr/ipcim/song_ui/src/mongoengine/mongoengine/base.py", line 444, in subclass_exception
return type(name, parents, {'__module__': module})
TypeError: Error when calling the metaclass bases
Cannot create a consistent method resolution order (MRO) for bases DoesNotExist, DoesNotExist
```

reverting to 00c8d7e  fixes this issue

**Comment by iapain** [comment] 2010-04-13 08:15
It looks like a diamond problem. I suspect problem exist when Multiple Inheritance come across. I have noted the bug and will be fixed ASAP.

**Comment by iapain** [comment] 2010-04-13 20:07
@StuartMitchell Could you please post your Model code and Python version? I was not able to repeat this problem.

**Comment by StuartMitchell** [comment] 2010-04-15 23:29
hi been a bit busy and will only be able to do this next week.
It is part of a rather large commercial application so I will have to extract a test case from it.

**Comment by flosch** [comment] 2010-04-17 11:38
Seems to be a duplicate of http://github.com/hmarr/mongoengine/issues#issue/40. I posted an example, too.

**Comment by hmarr** [comment] 2010-04-17 20:49
I've just pushed a fix for this - should (hopefully) sort the problem.

**Comment by flosch** [comment] 2010-04-17 20:51
Big thanks! I'm going to test it.

**Comment by flosch** [comment] 2010-04-17 20:53
Works for me :) Seems to be fixed.

**Comment by hmarr** [comment] 2010-04-17 21:02
Cool, cheers

**Closed as completed by hmarr** 2010-04-17 21:02 UTC

**Comment by StuartMitchell** [comment] 2010-04-18 21:32
Well I don't get the error anymore,  but I can't say if it is working because of api changes on get_or_create. 
Decided that I'll not follow trunk anymore (only did that because I needed DictField, I'd prefer to use released code) and will pin the code on my last working revision.

Thanks again
Stu

**Comment by iapain** [comment] 2010-04-19 18:12
Cool, I also confirm, its fixed. Thanks Harry! Cheers
